name: sparse-ho-env

dependencies:
    - ipython
    - numpy
    - scipy>=1.4.1
    - scikit-learn>=0.21
    - numba
    - seaborn>=0.7
    - matplotlib>=2.0.0
    - pip

    - pip:
        - download
        - hyperopt
        - cvxpy
        - torch
        - cvxpylayers
        - git+https://github.com/mathurinm/celer.git
